"""Evidence-first contract document parsing primitives."""

from .models import (
    AttachmentReference,
    ApplicabilitySpec,
    BoundingBox,
    ContractFact,
    ContractPackage,
    DecisionType,
    Document,
    DocumentKind,
    DocumentNode,
    Evidence,
    EvidenceType,
    Finding,
    FindingStatus,
    KnowledgeChunk,
    LayoutBlock,
    Page,
    ParsedDocument,
    ParsedPage,
    ReviewRun,
    ReviewDecision,
    ReviewReport,
    ReviewResult,
    ReviewStatus,
    ReviewTransition,
    RetrievalHit,
    RetrievalTrace,
    SemanticReviewItem,
    SemanticReviewResponse,
    SemanticModelRequest,
    Rule,
    RuleBundle,
    RiskLevel,
    SourceLocator,
    TextToken,
)
from .parser import (
    DOCX_PARSER_VERSION,
    XLSX_PARSER_VERSION,
    PARSER_VERSION,
    ParseError,
    find_text_evidence,
    parse_document,
    parse_docx,
    parse_xlsx,
    parse_pdf,
    sha256_file,
)
from .ocr import OCRPageResult, OCRProviderError, OCRTextBlock, StaticOCRProvider
from .rules import RuleBundleError, load_rule_bundle, validate_rule
from .review import check_attachment_completeness, compare_fact_values
from .replay import (
    ReplayVerification,
    build_replay_fingerprint,
    build_result_fingerprint,
    verify_replay_inputs,
)
from .run import ReviewRunError, advance_review_run, create_review_run
from .store import AuditStoreError, JsonAuditStore
from .audit import AuditReport, audit_result
from .report import REPORT_RENDERER_VERSION, render_markdown_report, write_markdown_report
from .knowledge import LexicalKnowledgeIndex, build_knowledge_corpus
from .facts import extract_tax_rate_facts
from .semantic import (
    DEFAULT_SYSTEM_INSTRUCTION,
    OpenAICompatibleSemanticReviewer,
    SemanticClientError,
    StaticSemanticReviewer,
    build_semantic_batch_request_fingerprint,
    build_semantic_request_fingerprint,
    findings_from_semantic_response,
    validate_semantic_response,
)
from .pipeline import (
    ReplayMismatch,
    finalize_review,
    parse_contract_package,
    record_review_decision,
    replay_review,
    run_review,
    run_review_with_semantic_client,
)

__all__ = [
    "BoundingBox",
    "ApplicabilitySpec",
    "AttachmentReference",
    "ContractFact",
    "ContractPackage",
    "DecisionType",
    "Document",
    "DocumentKind",
    "DocumentNode",
    "Evidence",
    "EvidenceType",
    "Finding",
    "FindingStatus",
    "KnowledgeChunk",
    "LayoutBlock",
    "Page",
    "ParsedDocument",
    "ParsedPage",
    "ParseError",
    "DOCX_PARSER_VERSION",
    "XLSX_PARSER_VERSION",
    "PARSER_VERSION",
    "ReviewRun",
    "ReviewRunError",
    "ReviewDecision",
    "ReviewReport",
    "ReviewResult",
    "ReviewStatus",
    "ReviewTransition",
    "RetrievalHit",
    "RetrievalTrace",
    "SemanticReviewItem",
    "SemanticReviewResponse",
    "SemanticModelRequest",
    "DEFAULT_SYSTEM_INSTRUCTION",
    "OpenAICompatibleSemanticReviewer",
    "SemanticClientError",
    "StaticSemanticReviewer",
    "AuditStoreError",
    "AuditReport",
    "audit_result",
    "REPORT_RENDERER_VERSION",
    "render_markdown_report",
    "write_markdown_report",
    "JsonAuditStore",
    "ReplayMismatch",
    "ReplayVerification",
    "Rule",
    "RuleBundle",
    "RuleBundleError",
    "RiskLevel",
    "SourceLocator",
    "TextToken",
    "find_text_evidence",
    "check_attachment_completeness",
    "compare_fact_values",
    "advance_review_run",
    "build_replay_fingerprint",
    "build_result_fingerprint",
    "build_knowledge_corpus",
    "extract_tax_rate_facts",
    "create_review_run",
    "finalize_review",
    "parse_contract_package",
    "record_review_decision",
    "replay_review",
    "run_review",
    "run_review_with_semantic_client",
    "LexicalKnowledgeIndex",
    "build_semantic_request_fingerprint",
    "build_semantic_batch_request_fingerprint",
    "findings_from_semantic_response",
    "validate_semantic_response",
    "load_rule_bundle",
    "parse_pdf",
    "parse_docx",
    "parse_xlsx",
    "parse_document",
    "sha256_file",
    "validate_rule",
    "verify_replay_inputs",
    "OCRPageResult",
    "OCRProviderError",
    "OCRTextBlock",
    "StaticOCRProvider",
]
